version: '3.8'

services:
  paig-opensource:
    image: paig-opensource-server:${VERSION}
    container_name: paig-opensource-container
    environment:
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./custom-conf:/opt/paig/custom-conf
      - ./scripts:/scripts
    networks:
      - app-network
    entrypoint: /bin/bash
    command: -c "paig run --port ${PORT} --host 0.0.0.0"

networks:
  app-network:
    external: true
