version: '3.8'

services:
  paig-opensource:
    image: paig-opensource-server:0.0.3
    container_name: paig-opensource-container
    ports:
      - "4545:4545"
    volumes:
      - ./custom-conf:/opt/paig/custom-conf
    networks:
      - app-network

networks:
  app-network:
    external: true
