version: '3.8'

services:
  paig-opensource:
    image: paig-securechat-server:${VERSION}
    container_name: paig-securechat-unsafe-container
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./custom-configs:/opt/paig/custom-configs
      - ./securechat:/opt/paig/securechat
      - ./data:/opt/paig/data
      - ./scripts:/scripts
    networks:
      - app-network
    entrypoint: /bin/bash
    command: -c "paig_securechat run --port ${PORT} --host 0.0.0.0"

networks:
  app-network:
    external: true
