version: '3.8'

services:
  paig-opensource:
    image: paig-securechat-server:0.0.1
    container_name: paig-securechat-safe-container
    ports:
      - "2525:2525"
    volumes:
      - ./custom-configs:/opt/paig/custom-configs
      - ./securechat:/opt/paig/securechat
      - ./data:/opt/paig/data
    networks:
      - app-network
    entrypoint: /bin/bash
    command: -c "paig_securechat run --port 2525 --host 0.0.0.0"

networks:
  app-network:
    external: true
