version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: welcome1
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    external: true
