version: '3.8'

services:
  paig-opensource:
    image: paig-opensource-server:${VERSION}
    container_name: paig-opensource-container
    environment:
      - PORT=${PAIG_OPENSOURCE_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "${PAIG_OPENSOURCE_PORT}:4545"
    volumes:
      - ./custom-conf:/opt/paig/custom-conf
      - ./scripts:/scripts
    networks:
      - app-network
    entrypoint: /bin/bash
    command: -c "paig run --port 4545 --host 0.0.0.0"

networks:
  app-network:
    external: true
